### ISSUE TITLE
Wrong Dashboard state being emitted

### ISSUE THREAD

**Issue by AshishSingh2001** [CCExtractor/ccextractorfluttergui#11]
Unnecessarily already present state is thrown in Dashboard State

1. Add a file (call it X for simplicity)
2. Add X again ( already selected popup will appear)
3. After this whatever (Delete , Add) you do it will show the already selected popup

**Expected behavior**
It is expected to not throw already selected popup when its not the case.

**Proposed Solution**
We are not unsetting the AlreadyPresent boolean to false in dashboard state either we should unset it

**Desktop
- OS: Ubuntu 20.04.3 LTS x86_64
- Kernel: 5.11.0-40-generic

**Comment by AshishSingh2001** [comment]
I would like to work on this issue please assign it to me.

**Comment by AshishSingh2001** [comment]
One more suggestion would be we emit a new state which is about failing to add a file and we can add more checks like already selected files , file format.

Tell me if i need to make a different issue for it or just add it here.

**Comment by Techno-Disaster** [comment]
> 

Why would adding a file fail? 🤔  also file format stuff is already handled in file picker code. and for selected already files we have the alreadyPresent bool

**Comment by ItsAdityaKSingh** [comment]
If this issue is not yet resolved, I would like to do the needful!
