### ISSUE TITLE
Installation guide causing errors

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/ccextractorfluttergui#20]
The installation guide mentions about changing to flutter channel master and then upgrading which is causing issues while running the app. 

<img width="1052" alt="Screenshot 2021-12-26 at 7 21 04 PM" src="https://user-images.githubusercontent.com/69353350/147410330-43ffa3d4-9fce-499f-8e61-d0a7b66783dd.png">

 It may happen that master channel does not have a stable version or the app requires some older components to work. Changing the channel to stable should work well.

**Comment by Techno-Disaster** [comment]
Don't have a mac so can't confirm, but others from ccx have tried this out and they have not faced this. Also master should work on macOS or flutter peeps would have fixed it already. 

We should start using stable though, but that is for another issue. (needs ci change, docs change and website change)
