### ISSUE TITLE
Scroll bar nonfunctionality report

### ISSUE THREAD

**Issue by Shantanu66** [CCExtractor/ccextractorfluttergui#32]
**Describe the bug**
Scroll bar in the log window in the dashboard screen seems to not function as intended when dragged while clicking upon it.

**To Reproduce**
1. Go to 'DashBoard/Logs'
2. Click and drag 'Scroll bar'
3. try to Scroll down and up

**Expected behavior**
The expected behaviour should be that the the window(Logs) should traverse vertically when the bar is dragged up/down.
**Screenshots**
![image](https://user-images.githubusercontent.com/64373963/149138775-1ea60252-edf8-4c32-9eff-41f9bdb1e81c.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Techno-Disaster** [comment]
Hmm, scroll wheel seems to work, but dragging does not. Could be a flutter issue

**Comment by Shantanu66** [comment]
Yeah the issue seems to be in the scroll bar let me see this through
