### ISSUE TITLE
Can't select MXF files from GUI on Windows.

### ISSUE THREAD

**Issue by RyLo2797** [CCExtractor/ccextractorfluttergui#39]
**Describe the bug**
The file select dialog doesn't allow you to select MXF files on Windows.

**To Reproduce**
1. Click "Add More Files"
2. Look at bottom right Video (*) dropdown menu. It doesn't filter for MXF files.

**Expected behavior**
The file select dialog should filter for ALL files that ccextractor supports. And maybe have an "All Files" option just in case.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CCExtractor Version 0.94

**Additional context**
Should be an easy fix, unless there's a reason it was excluded from the new GUI.

**Comment by julowe** [comment]
Adding to this. Ran into same problem with .mov files.
My temp fix was to type `*` in to the filename field and hit enter and you can then select any file (it also then worked to extract CCs from the one .mov file I tried).

same: Win 10, CCExtractor v0.94

Thanks!

**Comment by manoj1749** [comment]
This was an small issue, it can be solved by some small changes, shall I include it in the current pr I made?

**Comment by cfsmp3** [comment]
> This was an small issue, it can be solved by some small changes, shall I include it in the current pr I made?

Sure

**Comment by ANUSHRAV01** [comment]
@RyLo2797 is Issue completed or Can i contribute too.

**Comment by manoj1749** [comment]
a pr regarding this issue is made and it is merged, this issue will be closed soon.
