### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by Booloki** [CCExtractor/ccextractorfluttergui#40]
Hello,

As pubspec files are fixed using simple https because github actions, could release/tag a new version ?
This is for fixing currently broken Arch Linux AUR building ( https://aur.archlinux.org/packages/ccextractor-gui )

Thanks

**Comment by Techno-Disaster** [comment]
https://github.com/CCExtractor/ccextractorfluttergui/releases/tag/v0.6.0
