### ISSUE TITLE
Dnd support on desktop

### ISSUE THREAD

**Issue by Techno-Disaster** [CCExtractor/ccextractorfluttergui#6]
Flutter desktop drag and drop support with https://pub.dev/packages/desktop_drop

**Comment by AshishSingh2001** [comment]
Hey, I would like to work on this issue.

**Comment by manoj1749** [comment]
- Hey @Techno-Disaster , I had made a PR #41 which solves this issue
- Can you review it once?

**Comment by manoj1749** [comment]
- This Issue can be close as it is solved with the pr #41
